option(PROFILING "Profile the program" OFF)
option(USE_SCALAR "Use scalar operation rather than vectorization" OFF)
option(PROD "Production mode" OFF)
option(NO_PYTHON "Turn off python interface" OFF)
option(NO_BOUND_CHECK "Turn off bound checking" OFF)
option(NO_STATE_CHECK "Turn off state checking" OFF)
option(NEED_SPEED "Enable to get the most speed" OFF)
