if (CMAKE_HOST_SYSTEM_NAME STREQUAL "Linux")
	target_compile_definitions(CompilerFlags INTERFACE SYS_LINUX)
elseif(CMAKE_HOST_SYSTEM_NAME STREQUAL "Windows")
	target_compile_definitions(CompilerFlags INTERFACE SYS_WINDOWS)
elseif(CMAKE_HOST_SYSTEM_NAME STREQUAL "Darwin")
	target_compile_definitions(CompilerFlags INTERFACE SYS_MACOS)
else()
	target_compile_definitions(CompilerFlags INTERFACE SYS_UNKNOWN)
endif()
